### ISSUE TITLE
Shared volume of lago-api and lago-worker

### ISSUE THREAD

**Issue by grthr** [getlago/lago-helm-charts#24]
Can you provide any information about the shared volume which is mounted at `/app/storage`?

What kind of data is stored in there? why is it needed to be shared across all pods of lago-api deployment and lago-worker deployment? 
We are using Longhorn as a storage backend and therefor need to avoid PersistentVolumeClaims in RWX mode.

Thanks in advance for clarification.

**Comment by jdenquin** [comment]
@grthr storage on PVC is used to store assets (like Organization logo) and invoice's PDF.
Both API and Worker can write and read on it thats why it requires RWM, I would recommend to use S3 as a PVC replacement, we do not need performances around those topics.

**Comment by grthr** [comment]
Thanks for the quick response. Actually, I now configured my test deployment without the shared volume.

PDF invoices seem to work so far. I can download them via frontend without any issues. Can't tell about Organization logos as I'm not using any.

Maybe this helps getting rid of the requirement of having an RWX volume.

**Comment by maximiliend** [comment]
Hi !

I strongly agree on a S3 (Cloud provider or Self-Hosted) backend for file storage.

But in case of some peoples still want to use a shared volume, I created a PR 
#44  for allowing this to work with a RWX. If needed this could be improved with conditionals variables.

**Comment by roeeklinger** [comment]
Hey!

I just wanted to say that I just tried to deploy Lago for the first time as a first time Lago user and ran into this same problem on a Rancher cluster, was about to open an issue before I luckily found this.

is it safe to run this with RWX as #44 suggests or must I configure S3?

I also agree that this should be documented / patched out since currently when you try to deploy the charts for the first time with the default configs, the deployment fails with something like:
`Multi-Attach error for volume "pvc-" Volume is already used by pod(s) lago-api, lago-worker`

It's documented and hard to miss that `frontUrl` and `apiUrl` need to be configured to deploy, but nothing is mentioned about the PVC, so it's easy to get confused as happened to me.

Thanks!
